### ISSUE TITLE
Add benchmarks for insert / read

### ISSUE THREAD

**Issue by taoshengshi** [RangerMauve/ipld-prolly-indexer#4]

**Comment by RangerMauve** [comment]
- use some standard benchmarking library
- insert thousands of random records and measure perofrmance. records should have primary keys and several fields
- same thing but with an index over one of the fields
- same but two indexes over seperate fields
- same but with an index with two fields
- same tests but try different batch insert sizes

Would also be cool if we could have a way to measure memory usage
