### ISSUE TITLE
Add merge operation to indexer

### ISSUE THREAD

**Issue by taoshengshi** [RangerMauve/ipld-prolly-indexer#5]

**Comment by RangerMauve** [comment]
New `Merge(blockstore, ...dbs Database) : Database` function.
Should check that the prolly tree configs are the same in them and do a merge at the prolly tree level. Any overlapping keys will be a "last write wins" where later DBs overwrite earlier ones.

Ideally the merge should skip over ranges that don't overlap and avoid rebuilding the entire tree.
