### ISSUE TITLE
[Demo] Modify "get proof" to return an IPLD path for the cid/index path to get to the record

### ISSUE THREAD

**Issue by taoshengshi** [RangerMauve/ipld-prolly-indexer#8]

**Comment by RangerMauve** [comment]
We should return a [Datamodel Path](https://github.com/ipld/go-ipld-prime/blob/master/datamodel/path.go#L64) from the root cid to the specific index in the `values` that the data lives.

Note that the path should use the raw IPLD values without the schema wrapping.

Alternately maybe we should return an IPLD URL which _does_ have the schema wrapping it? Thoughts? https://github.com/RangerMauve/js-ipld-url-resolve/

**Comment by sssion** [comment]
@RangerMauve do you mean this? []PathSegment{{s: cidStr1, i: -1}, {s: cidStr2, i: -1}, {s: cidStr3, i: -1}} (equals with ParsePath("/cidStr1/cidStr2/cidStr3"),   cid1 cid2 cid3 mean the path in ProllyTree from root to the leaf node(contains the data record))

**Comment by RangerMauve** [comment]
Yes exactly! Note that most of the path will be indexes since we use tuple encoding in the schema
